# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('background', models.CharField(default='rgba(00, 80, FF, 0.8)', max_length=200)),
                ('is_all_day', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myscheduler.EventType'),
        ),
    ]
